# Cluster config file : 

apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31080
        hostPort: 8082
      - containerPort: 32443
        hostPort: 8444
